server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: 'GET, POST, PUT, DELETE'
            allowed-headers: 'Content-Type, Authorization'
      routes:
        - id: backend
          uri: http://theanh2906.ddns.net:8081
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"