server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: '*'
      routes:
        - id: backend
          uri: http://localhost:8081
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/(?<segment>.*), /$\{segment}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS
              allowedHeaders: '*'
management:
  endpoints:
    web:
      exposure:
        include: "*"