spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://localhost:8081
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"