server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://theanh2906.ddns.net:8081
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"