server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: '*'
      routes:
        - id: backend
          uri: http://theanh2906.ddns.net:8081
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"